name: Auto Merge Main to Test

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge Main to Test
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

          git checkout test
          git merge main --no-ff -m "Auto-merge changes from main branch"
          
          git push origin test
